(defconst vietnam-public-holidays
  '((holiday-fixed 1 1 "Tết Dương Lịch")
    (holiday-chinese 12 30 "Tất niên")
    (holiday-chinese 1 1 "Tết Nguyên Đán")
    (holiday-chinese 1 2 "Tết Nguyên Đán")
    (holiday-chinese 1 3 "Tết Nguyên Đán")
    (holiday-chinese 1 4 "Tết Nguyên Đán")
    (holiday-chinese 3 10 "Giỗ Tổ Hùng Vương")
    (holiday-fixed 4 30 "Ngày Giải phóng miền Nam, Thống nhất đất nước")
    (holiday-fixed 5 1 "Ngày Quốc tế Lao động")
    (holiday-fixed 9 2 "Ngày Quốc khánh"))
  "Pre-defined vietnam public holidays.")

(defconst vietnam-traditional-holidays
  '((holiday-chinese 3 1 "Hội Phủ Dầy")
    (holiday-chinese 3 2 "Hội Phủ Dầy")
    (holiday-chinese 3 3 "Hội Phủ Dầy")
    (holiday-chinese 3 4 "Hội Phủ Dầy")
    (holiday-chinese 3 5 "Hội Phủ Dầy")
    (holiday-chinese 3 6 "Hội Phủ Dầy")
    (holiday-chinese 3 7 "Hội Phủ Dầy")
    (holiday-chinese 3 8 "Hội Phủ Dầy")
    (holiday-chinese 3 9 "Hội Phủ Dầy")
    (holiday-chinese 3 10 "Hội Phủ Dầy Định")
    (holiday-chinese 3 4 "Hội đền Hai Bà Trưng")
    (holiday-chinese 1 4 "Hội Liễu Đôi")
    (holiday-chinese 1 8 "Hội Chùa Đậu")
    (holiday-chinese 1 9 "Hội Chùa Đậu")
    (holiday-chinese 1 10 "Hội Chùa Đậu")
    (holiday-chinese 12 12 "Hội Đống Đa")
    (holiday-chinese 1 6 "Hội Chùa Hương (đến hết tháng 3)")
    (holiday-chinese 1 10 "Lễ hội đua Voi")
    (holiday-chinese 1 13 "Hội Lim")
    (holiday-chinese 12 10 "Hội Côn Sơn")
    (holiday-chinese 1 15 "Hội Xuân Núi Bà")
    (holiday-chinese 3 6 "Hội Chùa Tây Phương")
    (holiday-chinese 3 4 "Hội đền Thờ Hai Bà Trưng")
    (holiday-chinese 3 5 "Hội đền Thờ Hai Bà Trưng")
    (holiday-chinese 3 6 "Hội đền Thờ Hai Bà Trưng")
    (holiday-chinese 3 14 "Lễ hội Gò Tháp")
    (holiday-chinese 3 15 "Lễ hội Gò Tháp")
    (holiday-chinese 3 16 "Lễ hội Gò Tháp")
    (holiday-chinese 11 14 "Lễ hội Gò Tháp")
    (holiday-chinese 11 15 "Lễ hội Gò Tháp")
    (holiday-chinese 11 16 "Lễ hội Gò Tháp")
    (holiday-chinese 3 7 "Hội Chùa Thầy")
    (holiday-chinese 3 9 "Lễ hội Hoa Lư")
    (holiday-chinese 3 10 "Giỗ Tổ Hùng Vương")
    (holiday-chinese 3 1 "Hội Đâm Trâu (đến hết tháng 3)")
    (holiday-chinese 4 9 "Hội Gióng")
    (holiday-chinese 4 23 "Hội Bà Chúa Xứ")
    (holiday-chinese 8 2 "Hội Lăng Lê Văn Duyệt")
    (holiday-chinese 8 9 "Hội Chọi Trâu Đồ Sơn")
    (holiday-chinese 8 16 "Hội Nghinh Ông")
    (holiday-chinese 8 20 "Hội Côn Sơn")
    )
  "Pre-defined vietnam traditional holidays.")

(defconst vietnam-other-holidays
  '((holiday-fixed 1 9 "Ngày Học sinh - Sinh viên Việt Nam")
    (holiday-fixed 2 3 "Ngày thành lập Đảng Cộng sản Việt Nam")
    (holiday-fixed 2 27 "Ngày Thầy thuốc Việt Nam")
    (holiday-fixed 3 8 "Ngày Quốc tế Phụ nữ")
    (holiday-fixed 3 20 "Ngày Quốc tế Hạnh phúc")
    (holiday-fixed 3 22 "Ngày Nước sạch Thế giới")
    (holiday-fixed 3 26 "Ngày thành lập Đoàn Thanh niên Cộng sản Hồ Chí Minh")
    (holiday-fixed 3 27 "Ngày Thể thao Việt Nam")
    (holiday-fixed 3 28 "Ngày thành lập lực lượng Dân quân tự vệ")
    (holiday-fixed 4 21 "Ngày Sách Việt Nam")
    (holiday-fixed 4 22 "Ngày Trái đất")
    (holiday-fixed 4 30 "Ngày giải phóng Miền Nam thống nhất đất nước")
    (holiday-fixed 5 1 "Quốc tế lao động")
    (holiday-fixed 5 7 "Ngày chiến thắng Điện Biên Phủ")
    (holiday-fixed 5 15 "Ngày thành lập Đội Thiếu niên Tiền phong Hồ Chí Minh")
    (holiday-fixed 5 19 "Ngày sinh của Chủ tịch Hồ Chí Minh")
    (holiday-fixed 6 1 "Ngày Quốc tế Thiếu nhi")
    (holiday-fixed 6 5 "Ngày môi trường thế giới, Ngày Bác Hồ ra đi tìm đường cứu nước")
    (holiday-fixed 6 28 "Ngày Gia đình Việt Nam")
    (holiday-fixed 7 27 "Ngày Thương binh Liệt sĩ")
    (holiday-fixed 8 19 "Ngày Cách mạng tháng Tám thành công")
    (holiday-fixed 9 2 "Ngày Quốc khánh nước Cộng hoà Xã hội Chủ nghĩa Việt Nam")
    (holiday-fixed 9 7 "Ngày thành lập Đài Truyền hình Việt Nam")
    (holiday-fixed 10 13 "Ngày Doanh nhân Việt Nam")
    (holiday-fixed 10 20 "Ngày thành lập Hội Phụ nữ Việt Nam")
    (holiday-fixed 11 20 "Ngày Nhà giáo Việt Nam")
    (holiday-fixed 12 22 "Ngày thành lập Quân đội Nhân dân Việt Nam")
    (holiday-fixed 12 25 "Ngày Lễ Giáng Sinh")
    (holiday-chinese 1 15 "Tết Nguyên Tiêu")
    (holiday-chinese 3 3 "Tết Hàn Thực")
    (holiday-chinese 4 15 "Lễ Phật Đản")
    (holiday-chinese 5 5 "Tết Đoan Ngọ")
    (holiday-chinese 7 15 "Lễ Vu Lan/Lễ Xá Tội Vong Nhân")
    (holiday-chinese 8 15 "Tết Trung Thu")
    (holiday-chinese 12 23 "Ông Táo về trời")
    )
  "Pre-defined vietnam other holidays.")

(defun vietnam-holidays-setup ()
  (setq calendar-holidays
        (append calendar-holidays vietnam-public-holidays vietnam-traditional-holidays vietnam-other-holidays))
  )

(provide 'vietnam-holidays)
